// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA41GXRKPghRkHC3TgtXATsj82-NNjUB2Y',
    appId: '1:678125850488:web:dfd55d7ee8be622cc4028d',
    messagingSenderId: '678125850488',
    projectId: 'class-assignment-2f405',
    authDomain: 'class-assignment-2f405.firebaseapp.com',
    storageBucket: 'class-assignment-2f405.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWaS0Od1OWMv0AcCg-jpxi0-ajB5zINk',
    appId: '1:678125850488:android:5067ef914b91add7c4028d',
    messagingSenderId: '678125850488',
    projectId: 'class-assignment-2f405',
    storageBucket: 'class-assignment-2f405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBGlvjz_IlI9Nt4ZXS0kw9e5AeCgCkyg',
    appId: '1:678125850488:ios:0265eb561a30e782c4028d',
    messagingSenderId: '678125850488',
    projectId: 'class-assignment-2f405',
    storageBucket: 'class-assignment-2f405.appspot.com',
    iosClientId: '678125850488-k4cd9hi75854oefejbpdsloptkvn80p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.classAssignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVBGlvjz_IlI9Nt4ZXS0kw9e5AeCgCkyg',
    appId: '1:678125850488:ios:0265eb561a30e782c4028d',
    messagingSenderId: '678125850488',
    projectId: 'class-assignment-2f405',
    storageBucket: 'class-assignment-2f405.appspot.com',
    iosClientId: '678125850488-k4cd9hi75854oefejbpdsloptkvn80p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.classAssignment2',
  );
}
